name: Python Face Recognize 

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push  
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: taqsim/face_cam:latest
          no-cache: true 
  deploy:    
    runs-on: ubuntu-latest
    needs: dockerize
    steps:
      - name: executing remote ssh commands using keys
        id: deploy
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 20m
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEV_SSH_PORT }}
          script: |
            echo "Copying settings to server..."
            echo "Pulling latest docker image and restarting backend app..."
            docker pull taqsim/face_cam:latest && docker restart face_cam
            
